#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: student-redis-sample
  namespace: #@ data.values.workload_namespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: student-redis-sample
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"  
  serviceClaims: 
    - name: redis
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: #@ data.values.instance_name
  source:
    git:
      url: https://github.com/gm2552/redis-secret-template.git
      ref:
        branch: main
    subPath: student-redis-sample